import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useAI } from '../../context/AIContext';
import { geminiService } from '../../services/geminiService';
import { ProductImage, GeneratedResult, AspectRatio } from '../../types/nexpose';
import { HolographicCard } from '../ui/HolographicCard';
import { NeonButton } from '../ui/NeonButton';
import { GlowTextArea, GlowInput } from '../ui/GlowInput';
import { UploadZone } from '../ui/UploadZone';
import { 
  Sparkles, Upload, X, Image as ImageIcon, 
  Maximize2, Copy, Film, AlertCircle, CheckCircle2, Loader2
} from 'lucide-react';
import { cn } from '../../lib/utils';

export const NEXPoseContainer: React.FC = () => {
  const { getKey, toast } = useAI();
  const [activeStep, setActiveStep] = useState(1);
  
  // State Data
  const [productImages, setProductImages] = useState<ProductImage[]>([]);
  const [modelImage, setModelImage] = useState<ProductImage | null>(null);
  const [description, setDescription] = useState('');
  const [theme, setTheme] = useState('');
  const [aspectRatio, setAspectRatio] = useState<AspectRatio>('16:9');
  
  // State Proses
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [isAutoDescribing, setIsAutoDescribing] = useState(false);
  const [results, setResults] = useState<GeneratedResult[]>([]);
  
  // Modal State
  const [modalContent, setModalContent] = useState<{ title: string; content: React.ReactNode } | null>(null);

  // Refs
  const productInputRef = useRef<HTMLInputElement>(null);
  const modelInputRef = useRef<HTMLInputElement>(null);

  // --- Handlers ---

  const handleFileProcess = (files: FileList | null, type: 'product' | 'model') => {
    if (!files) return;

    Array.from(files).forEach(file => {
      const reader = new FileReader();
      reader.onload = (e) => {
        const base64Raw = e.target?.result as string;
        const base64 = base64Raw.split(',')[1];
        const mimeType = base64Raw.match(/:(.*?);/)?.[1] || 'image/jpeg';
        
        const newImage: ProductImage = {
          id: Math.random().toString(36).substr(2, 9),
          base64,
          mimeType,
          file
        };

        if (type === 'product') {
          setProductImages(prev => [...prev, newImage]);
        } else {
          setModelImage(newImage);
        }
      };
      reader.readAsDataURL(file);
    });
  };

  const handleAutoDescription = async () => {
    const apiKey = getKey('gemini');
    if (!apiKey) return toast.show("API Key Gemini diperlukan.", 'error');
    if (productImages.length === 0) return toast.show("Upload foto produk terlebih dahulu.", 'error');

    setIsAutoDescribing(true);
    try {
      const desc = await geminiService.autoGenerateDescription(apiKey, productImages);
      setDescription(desc);
      toast.show("Deskripsi berhasil dibuat!", 'success');
    } catch (error) {
      toast.show("Gagal membuat deskripsi otomatis.", 'error');
    } finally {
      setIsAutoDescribing(false);
    }
  };

  const handleGenerate = async () => {
    const apiKey = getKey('gemini');
    if (!apiKey) return toast.show("API Key Gemini diperlukan.", 'error');
    if (productImages.length === 0) return toast.show("Foto produk wajib diisi.", 'error');
    if (!description) return toast.show("Deskripsi produk wajib diisi.", 'error');

    setIsAnalyzing(true);
    setResults([]); // Reset results

    try {
      // 1. Analisis & Generate Prompts
      const concepts = await geminiService.analyzeAndGeneratePrompts(
        apiKey, productImages, modelImage, description, theme, aspectRatio
      );

      // 2. Siapkan Placeholder Results
      const initialResults: GeneratedResult[] = concepts.map((c, idx) => ({
        id: `res-${idx}`,
        title: c.title,
        prompt: c.prompt,
        status: 'loading',
        // Mocking image URL for demo purposes since real image gen API is restricted
        // In production, this would call the image generation endpoint
        imageUrl: `https://picsum.photos/seed/${Math.random()}/800/600` 
      }));

      setResults(initialResults);

      // Simulasi Loading per gambar (karena API image gen asli butuh waktu)
      initialResults.forEach((res, idx) => {
        setTimeout(() => {
          setResults(prev => prev.map(r => 
            r.id === res.id ? { ...r, status: 'completed' } : r
          ));
        }, 2000 + (idx * 1500));
      });

    } catch (error) {
      toast.show("Gagal memproses permintaan.", 'error');
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleCaptionGen = async (res: GeneratedResult) => {
    const apiKey = getKey('gemini');
    if (!apiKey) return;
    
    setModalContent({
      title: "✨ Magic Caption",
      content: <div className="flex justify-center p-8"><Loader2 className="animate-spin w-8 h-8 text-neon-teal"/></div>
    });

    try {
      const caption = await geminiService.generateCaption(apiKey, productImages, description, res.title);
      setModalContent({
        title: "✨ Magic Caption",
        content: (
          <div className="space-y-4">
            <div className="bg-black/40 p-4 rounded-xl border border-white/10 text-sm text-gray-300 whitespace-pre-wrap font-mono">
              {caption}
            </div>
            <NeonButton fullWidth onClick={() => {
              navigator.clipboard.writeText(caption);
              toast.show("Caption disalin!", 'success');
            }}>
              <Copy className="w-4 h-4" /> Salin Caption
            </NeonButton>
          </div>
        )
      });
    } catch (e) {
      setModalContent(null);
      toast.show("Gagal membuat caption.", 'error');
    }
  };

  // --- Render Helpers ---

  const AspectRatioBtn = ({ ratio, label }: { ratio: AspectRatio, label: string }) => (
    <button
      onClick={() => setAspectRatio(ratio)}
      className={cn(
        "flex flex-col items-center justify-center p-3 rounded-xl border transition-all duration-300",
        aspectRatio === ratio 
          ? "bg-neon-teal/10 border-neon-teal text-neon-teal shadow-[0_0_10px_rgba(0,243,255,0.2)]" 
          : "bg-white/5 border-white/10 text-white/40 hover:bg-white/10 hover:text-white"
      )}
    >
      <div className={cn(
        "border-2 mb-2 rounded-sm",
        ratio === '1:1' ? 'w-6 h-6' : 
        ratio === '16:9' ? 'w-8 h-4.5' : 
        ratio === '9:16' ? 'w-4.5 h-8' : 'w-5 h-6',
        aspectRatio === ratio ? "border-neon-teal" : "border-current"
      )} />
      <span className="text-xs font-bold">{label}</span>
    </button>
  );

  return (
    <div className="flex flex-col lg:flex-row gap-8 h-[calc(100vh-140px)]">
      {/* --- LEFT PANEL (CONTROLS) --- */}
      <div className="w-full lg:w-[420px] flex-shrink-0 overflow-y-auto pr-2 custom-scrollbar pb-10">
        <HolographicCard className="p-6 space-y-8">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-600 to-neon-purple flex items-center justify-center shadow-neon-purple/50">
              <Sparkles className="w-5 h-5 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">NEXPose Studio</h2>
              <p className="text-xs text-white/40">AI Product Photography</p>
            </div>
          </div>

          {/* Step 1: Product Images */}
          <div className="space-y-3">
            <div className="flex justify-between items-center">
              <label className="text-sm font-bold text-white flex items-center gap-2">
                <span className="w-5 h-5 rounded-full bg-neon-teal/20 text-neon-teal flex items-center justify-center text-xs">1</span>
                Foto Produk
              </label>
              <span className="text-[10px] bg-white/10 px-2 py-0.5 rounded text-white/50">Wajib</span>
            </div>
            
            <div 
              onClick={() => productInputRef.current?.click()}
              className={cn(
                "border-2 border-dashed rounded-xl p-6 transition-all cursor-pointer flex flex-col items-center justify-center text-center gap-2 group",
                productImages.length > 0 
                  ? "border-neon-teal/50 bg-neon-teal/5" 
                  : "border-white/10 hover:border-white/30 hover:bg-white/5"
              )}
            >
              <input 
                type="file" 
                multiple 
                accept="image/*" 
                className="hidden" 
                ref={productInputRef}
                onChange={(e) => handleFileProcess(e.target.files, 'product')}
              />
              <Upload className={cn("w-8 h-8 transition-colors", productImages.length > 0 ? "text-neon-teal" : "text-white/30 group-hover:text-white")} />
              <p className="text-xs text-white/50">Klik untuk upload foto produk</p>
            </div>

            {productImages.length > 0 && (
              <div className="grid grid-cols-4 gap-2 animate-in fade-in slide-in-from-top-2">
                {productImages.map((img) => (
                  <div key={img.id} className="relative aspect-square rounded-lg overflow-hidden group border border-white/10">
                    <img src={`data:${img.mimeType};base64,${img.base64}`} className="w-full h-full object-cover" />
                    <button 
                      onClick={() => setProductImages(prev => prev.filter(p => p.id !== img.id))}
                      className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 flex items-center justify-center text-red-400 transition-all"
                    >
                      <X className="w-4 h-4" />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Step 2: Description */}
          <div className="space-y-3">
            <div className="flex justify-between items-center">
              <label className="text-sm font-bold text-white flex items-center gap-2">
                <span className="w-5 h-5 rounded-full bg-neon-teal/20 text-neon-teal flex items-center justify-center text-xs">2</span>
                Deskripsi
              </label>
              <button 
                onClick={handleAutoDescription}
                disabled={isAutoDescribing || productImages.length === 0}
                className="text-[10px] flex items-center gap-1 bg-indigo-500/20 hover:bg-indigo-500/40 text-indigo-300 px-2 py-1 rounded transition-colors disabled:opacity-50"
              >
                {isAutoDescribing ? <Loader2 className="w-3 h-3 animate-spin"/> : <Sparkles className="w-3 h-3"/>}
                Auto-Magic
              </button>
            </div>
            <GlowTextArea 
              rows={3} 
              placeholder="Jelaskan produk Anda..." 
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="text-sm"
            />
          </div>

          {/* Step 3: Model (Optional) */}
          <div className="space-y-3">
            <label className="text-sm font-bold text-white flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-white/10 text-white/60 flex items-center justify-center text-xs">3</span>
              Model Referensi <span className="text-[10px] text-white/30 font-normal ml-auto">(Opsional)</span>
            </label>
            
            {!modelImage ? (
              <div 
                onClick={() => modelInputRef.current?.click()}
                className="border border-dashed border-white/10 rounded-xl p-3 flex items-center justify-center gap-2 cursor-pointer hover:bg-white/5 transition-colors"
              >
                <input 
                  type="file" 
                  accept="image/*" 
                  className="hidden" 
                  ref={modelInputRef}
                  onChange={(e) => handleFileProcess(e.target.files, 'model')}
                />
                <ImageIcon className="w-4 h-4 text-white/40" />
                <span className="text-xs text-white/40">Upload Model</span>
              </div>
            ) : (
              <div className="relative h-24 rounded-xl overflow-hidden border border-white/10 group">
                <img src={`data:${modelImage.mimeType};base64,${modelImage.base64}`} className="w-full h-full object-cover" />
                <button 
                  onClick={() => setModelImage(null)}
                  className="absolute top-2 right-2 p-1 bg-red-500/80 rounded-md text-white opacity-0 group-hover:opacity-100 transition-opacity"
                >
                  <X className="w-3 h-3" />
                </button>
              </div>
            )}
          </div>

          {/* Step 4: Config */}
          <div className="grid grid-cols-1 gap-4">
            <div className="space-y-2">
              <label className="text-xs font-bold text-white/60 uppercase">Tema Visual</label>
              <GlowInput 
                placeholder="Contoh: Cyberpunk, Minimalis, Alam..." 
                value={theme}
                onChange={(e) => setTheme(e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <label className="text-xs font-bold text-white/60 uppercase">Rasio Aspek</label>
              <div className="grid grid-cols-4 gap-2">
                <AspectRatioBtn ratio="16:9" label="16:9" />
                <AspectRatioBtn ratio="9:16" label="9:16" />
                <AspectRatioBtn ratio="1:1" label="1:1" />
                <AspectRatioBtn ratio="4:5" label="4:5" />
              </div>
            </div>
          </div>

          <NeonButton 
            fullWidth 
            size="lg" 
            onClick={handleGenerate}
            disabled={isAnalyzing}
            className="mt-4"
          >
            {isAnalyzing ? (
              <span className="flex items-center gap-2">
                <Loader2 className="w-5 h-5 animate-spin" /> Memproses...
              </span>
            ) : (
              <span className="flex items-center gap-2">
                <Sparkles className="w-5 h-5" /> Generate Konsep
              </span>
            )}
          </NeonButton>

        </HolographicCard>
      </div>

      {/* --- RIGHT PANEL (RESULTS) --- */}
      <div className="flex-1 overflow-y-auto custom-scrollbar pb-10">
        {results.length === 0 ? (
          <div className="h-full flex flex-col items-center justify-center text-center p-10 border-2 border-dashed border-white/5 rounded-3xl bg-white/[0.02]">
            <div className="w-24 h-24 rounded-full bg-white/5 flex items-center justify-center mb-6 animate-pulse-slow">
              <ImageIcon className="w-10 h-10 text-white/20" />
            </div>
            <h3 className="text-2xl font-bold text-white mb-2">Galeri Kosong</h3>
            <p className="text-white/40 max-w-sm">
              Unggah produk dan klik Generate untuk melihat keajaiban AI.
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {results.map((res) => (
              <HolographicCard key={res.id} className="p-4 group flex flex-col gap-3 animate-in fade-in slide-in-from-bottom-4 duration-500">
                <div className="flex justify-between items-start">
                  <h3 className="font-bold text-white line-clamp-1">{res.title}</h3>
                  {res.status === 'completed' && <CheckCircle2 className="w-4 h-4 text-neon-teal" />}
                </div>

                <div className={cn(
                  "relative rounded-xl overflow-hidden bg-black/50 border border-white/5",
                  aspectRatio === '1:1' ? 'aspect-square' : 
                  aspectRatio === '9:16' ? 'aspect-[9/16]' : 
                  aspectRatio === '4:5' ? 'aspect-[4/5]' : 'aspect-video'
                )}>
                  {res.status === 'loading' ? (
                    <div className="absolute inset-0 flex items-center justify-center">
                      <div className="flex flex-col items-center gap-3">
                        <div className="w-8 h-8 border-2 border-neon-teal border-t-transparent rounded-full animate-spin" />
                        <span className="text-xs text-neon-teal animate-pulse">Rendering...</span>
                      </div>
                    </div>
                  ) : res.status === 'completed' ? (
                    <>
                      <img src={res.imageUrl} alt={res.title} className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" />
                      
                      {/* Overlay Actions */}
                      <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex items-end justify-center p-4">
                        <div className="flex gap-2">
                          <button 
                            onClick={() => handleCaptionGen(res)}
                            className="p-2 rounded-lg bg-white/10 backdrop-blur-md hover:bg-white/20 text-white transition-colors"
                            title="Buat Caption"
                          >
                            <span className="text-xs font-bold">📝 Caption</span>
                          </button>
                          <button 
                            onClick={() => setModalContent({
                              title: "Preview",
                              content: <img src={res.imageUrl} className="w-full h-auto rounded-lg" />
                            })}
                            className="p-2 rounded-lg bg-white/10 backdrop-blur-md hover:bg-white/20 text-white transition-colors"
                          >
                            <Maximize2 className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                    </>
                  ) : (
                    <div className="absolute inset-0 flex items-center justify-center text-red-400 gap-2">
                      <AlertCircle className="w-5 h-5" /> Gagal
                    </div>
                  )}
                </div>

                <div className="bg-white/5 rounded-lg p-3 text-[10px] text-white/40 font-mono line-clamp-2 group-hover:line-clamp-none transition-all">
                  {res.prompt}
                </div>
              </HolographicCard>
            ))}
          </div>
        )}
      </div>

      {/* --- UNIVERSAL MODAL --- */}
      <AnimatePresence>
        {modalContent && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center px-4">
            <motion.div 
              initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="absolute inset-0 bg-black/80 backdrop-blur-sm"
              onClick={() => setModalContent(null)}
            />
            <motion.div 
              initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.9, opacity: 0 }}
              className="relative w-full max-w-lg bg-[#0f172a] border border-white/10 rounded-2xl shadow-2xl overflow-hidden"
            >
              <div className="flex justify-between items-center p-4 border-b border-white/10 bg-white/5">
                <h3 className="font-bold text-white">{modalContent.title}</h3>
                <button onClick={() => setModalContent(null)} className="text-white/50 hover:text-white">
                  <X className="w-5 h-5" />
                </button>
              </div>
              <div className="p-4 max-h-[70vh] overflow-y-auto">
                {modalContent.content}
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};
