import React, { useState, useEffect } from 'react';
import { Play, Download, RefreshCw, Loader2, CheckCircle2, AlertTriangle, Zap } from 'lucide-react';
import { BasicMode } from './BasicMode';
import { ProMode } from './ProMode';
import { DuplicateMode } from './DuplicateMode';
import { StoryboardMode } from './StoryboardMode';
import { clsx } from 'clsx';
import { kieClient, KieJobStatus } from '../../lib/kieClient';
import { NeonButton } from '../../components/ui/NeonButton';
import { useAI } from '../../context/AIContext';
import { supabase } from '../../lib/supabase';

type TabMode = 'basic' | 'pro' | 'storyboard' | 'duplicate';

export const NexVideoGenerator = () => {
  const { toast } = useAI();
  const [activeTab, setActiveTab] = useState<TabMode>('basic');
  
  // Job State
  const [jobStatus, setJobStatus] = useState<KieJobStatus['status']>('idle');
  const [jobId, setJobId] = useState<string | null>(null);
  const [outputUrl, setOutputUrl] = useState<string | null>(null);
  const [progress, setProgress] = useState(0);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  
  // Unified Settings State
  const [settings, setSettings] = useState<any>({});

  // 1. Polling & Realtime Effect
  useEffect(() => {
    let interval: any;
    let channel: any;

    // A. Polling Mechanism (Client-side Worker)
    if ((jobStatus === 'queued' || jobStatus === 'processing') && jobId) {
      interval = setInterval(async () => {
        try {
          const status = await kieClient.getJobStatus(jobId);
          
          setJobStatus(status.status);
          if (status.progress) setProgress(status.progress);
          
          if (status.status === 'completed' && status.outputUrl) {
            setOutputUrl(status.outputUrl);
            toast.show('Video berhasil dibuat!', 'success');
          }
          if (status.status === 'failed') {
            setErrorMsg(status.errorMessage || 'Gagal membuat video.');
            toast.show(status.errorMessage || 'Gagal membuat video.', 'error');
          }
        } catch (e) {
          console.error("Polling error:", e);
        }
      }, 4000); // Poll every 4s
    }

    // B. Supabase Realtime Subscription (Listen for backend updates)
    if (jobId) {
      channel = supabase
        .channel(`job-${jobId}`)
        .on(
          'postgres_changes',
          {
            event: 'UPDATE',
            schema: 'public',
            table: 'generated_videos',
            filter: `task_id=eq.${jobId}`
          },
          (payload: any) => {
            console.log('🔔 Realtime Update:', payload);
            const newData = payload.new;
            
            if (newData.status === 'success' && newData.video_url) {
              setJobStatus('completed');
              setOutputUrl(newData.video_url);
              setProgress(100);
            } else if (newData.status === 'fail') {
              setJobStatus('failed');
              setErrorMsg(newData.meta_data?.error || 'Gagal');
            }
          }
        )
        .subscribe();
    }

    return () => {
      if (interval) clearInterval(interval);
      if (channel) supabase.removeChannel(channel);
    };
  }, [jobStatus, jobId, toast]);

  const handleGenerate = async () => {
    setJobStatus('queued');
    setOutputUrl(null);
    setProgress(0);
    setErrorMsg(null);
    
    try {
      console.log("Generating with settings:", settings);
      
      // Panggil Client Real (yang akan handle DB + API)
      const res = await kieClient.submitVideoJob({
        mode: activeTab,
        model: settings.model || 'sora-2-text-to-video',
        prompt: settings.prompt || settings.description || 'Video generated by NexusAI',
        duration: parseInt(settings.duration || '10'),
        aspectRatio: settings.aspectRatio || '9:16',
        resolution: settings.resolution || '1080p',
        assets: settings.assets,
        storyboardData: settings.storyboardData
      });

      setJobId(res.kieJobId); // Gunakan ID task untuk polling
      toast.show('Job dimulai! Mohon tunggu...', 'success');

    } catch (e: any) {
      setJobStatus('failed');
      setErrorMsg(e.message);
      toast.show(e.message, 'error');
    }
  };

  const tabs = [
    { id: 'basic', label: 'Basic' },
    { id: 'pro', label: 'Pro', badge: 'PRO' },
    { id: 'storyboard', label: 'Storyboard', badge: 'NEW' },
    { id: 'duplicate', label: 'Duplicate' },
  ];

  return (
    <div className="flex flex-col lg:flex-row gap-6 h-[calc(100vh-8rem)]">
      {/* Left Panel: Configuration */}
      <div className="w-full lg:w-1/2 flex flex-col gap-6 overflow-y-auto pr-2 custom-scrollbar">
        {/* Tabs */}
        <div className="flex p-1 bg-surface rounded-xl border border-border sticky top-0 z-20 backdrop-blur-xl overflow-x-auto">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as TabMode)}
              className={clsx(
                "flex-1 py-2.5 text-xs sm:text-sm font-medium rounded-lg transition-all flex items-center justify-center gap-2 whitespace-nowrap min-w-[80px]",
                activeTab === tab.id
                  ? "bg-primary text-white shadow-lg"
                  : "text-text-secondary hover:text-text-primary hover:bg-white/5"
              )}
            >
              {tab.label}
              {tab.badge && (
                <span className={clsx(
                  "text-[9px] font-bold px-1.5 py-0.5 rounded text-black",
                  tab.badge === 'PRO' ? "bg-gradient-to-r from-amber-400 to-orange-500" : "bg-neon-teal"
                )}>
                  {tab.badge}
                </span>
              )}
            </button>
          ))}
        </div>

        {/* Config Form */}
        <div className="bg-surface/50 border border-border rounded-2xl p-6 shadow-glow-purple/10 min-h-[400px]">
          {activeTab === 'basic' && <BasicMode onSettingsChange={setSettings} />}
          {activeTab === 'pro' && <ProMode onSettingsChange={setSettings} />}
          {activeTab === 'duplicate' && <DuplicateMode onSettingsChange={setSettings} />}
          {activeTab === 'storyboard' && <StoryboardMode onSettingsChange={setSettings} />}
        </div>
      </div>

      {/* Right Panel: Preview & Status */}
      <div className="w-full lg:w-1/2 flex flex-col gap-6">
        <div className="flex-1 bg-surface border border-border rounded-2xl p-1 relative overflow-hidden shadow-glow-cyan/10 group">
          {/* Status Overlay */}
          <div className="absolute top-4 right-4 z-20">
            {jobStatus === 'queued' && (
              <span className="flex items-center gap-2 px-3 py-1 rounded-full bg-yellow-500/20 text-yellow-400 border border-yellow-500/30 text-xs font-bold">
                <Loader2 className="w-3 h-3 animate-spin" /> Antrean
              </span>
            )}
            {jobStatus === 'processing' && (
              <span className="flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/20 text-blue-400 border border-blue-500/30 text-xs font-bold">
                <Loader2 className="w-3 h-3 animate-spin" /> Memproses {progress}%
              </span>
            )}
            {jobStatus === 'completed' && (
              <span className="flex items-center gap-2 px-3 py-1 rounded-full bg-success/20 text-success border border-success/30 text-xs font-bold">
                <CheckCircle2 className="w-3 h-3" /> Selesai
              </span>
            )}
            {jobStatus === 'failed' && (
              <span className="flex items-center gap-2 px-3 py-1 rounded-full bg-danger/20 text-danger border border-danger/30 text-xs font-bold">
                <AlertTriangle className="w-3 h-3" /> Gagal
              </span>
            )}
          </div>

          {/* Video Player or Placeholder */}
          <div className="w-full h-full bg-black/50 rounded-xl flex items-center justify-center relative overflow-hidden">
            {jobStatus === 'completed' && outputUrl ? (
              <video 
                src={outputUrl} 
                controls 
                autoPlay 
                loop 
                className="w-full h-full object-contain"
              />
            ) : (
              <div className="text-center p-8 max-w-md">
                {jobStatus === 'processing' || jobStatus === 'queued' ? (
                  <div className="flex flex-col items-center gap-4">
                    <div className="relative w-20 h-20">
                        <div className="absolute inset-0 border-4 border-white/10 rounded-full"></div>
                        <div className="absolute inset-0 border-4 border-t-secondary border-r-transparent border-b-transparent border-l-transparent rounded-full animate-spin"></div>
                        <div className="absolute inset-0 flex items-center justify-center font-mono text-lg font-bold text-white">{progress}%</div>
                    </div>
                    <p className="text-secondary animate-pulse font-medium">AI sedang bekerja...</p>
                    <p className="text-xs text-text-secondary">Estimasi waktu: 2-5 menit</p>
                  </div>
                ) : jobStatus === 'failed' ? (
                  <div className="flex flex-col items-center gap-4">
                    <AlertTriangle className="w-16 h-16 text-danger opacity-80" />
                    <p className="text-danger font-bold">Proses Gagal</p>
                    <p className="text-xs text-text-secondary bg-white/5 p-2 rounded border border-white/10">{errorMsg}</p>
                  </div>
                ) : (
                  <div className="flex flex-col items-center gap-4 opacity-30">
                    <div className="w-20 h-20 bg-white/10 rounded-full flex items-center justify-center">
                      <Play className="w-8 h-8 text-white" fill="currentColor" />
                    </div>
                    <p className="text-sm font-medium">Pratinjau akan muncul di sini</p>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>

        {/* Bottom Bar */}
        <div className="bg-surface border border-border rounded-2xl p-4 flex items-center justify-between">
          <div className="text-xs text-text-secondary">
            <p>Estimasi waktu: <span className="text-text-primary font-bold">~110s</span></p>
            <p>Biaya: <span className="text-secondary font-bold">150 kredit</span></p>
          </div>
          
          <div className="flex gap-3">
            {jobStatus === 'completed' && outputUrl && (
              <a href={outputUrl} download className="p-3 rounded-xl bg-white/5 hover:bg-white/10 text-text-primary transition-colors flex items-center justify-center">
                <Download className="w-5 h-5" />
              </a>
            )}
            
            <NeonButton
              onClick={handleGenerate}
              disabled={jobStatus === 'queued' || jobStatus === 'processing'}
              className={clsx(
                jobStatus === 'queued' || jobStatus === 'processing' ? "opacity-50 cursor-not-allowed" : ""
              )}
            >
              {jobStatus === 'completed' ? (
                <>
                  <RefreshCw className="w-4 h-4" /> Buat Lagi
                </>
              ) : (
                <>
                   <Zap className="w-4 h-4" /> Generate Video
                </>
              )}
            </NeonButton>
          </div>
        </div>
      </div>
    </div>
  );
};
